# Generated by Django 5.1 on 2024-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('num_quartos', models.SmallIntegerField(choices=[(1, 'UM'), (2, 'DOIS'), (3, 'TRES'), (4, 'QUATRO'), (5, 'CINCO'), (6, 'SEIS'), (7, 'SETE'), (8, 'OITO'), (9, 'NOVE OU MAIS')])),
                ('num_banheiros', models.SmallIntegerField(choices=[(1, 'UM'), (2, 'DOIS'), (3, 'TRES'), (4, 'QUATRO'), (5, 'CINCO'), (6, 'SEIS'), (7, 'SETE'), (8, 'OITO'), (9, 'NOVE OU MAIS')])),
                ('tipo', models.SmallIntegerField(choices=[(1, 'CASA'), (2, 'APARTAMENTO'), (3, 'FAZENDA'), (4, 'FLAT')])),
                ('area', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'ALUGUEL'), (2, 'VENDA'), (3, 'AMBOS')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='casa/fotos')),
            ],
        ),
    ]
