# Generated by Django 5.1 on 2024-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=50),
        ),
    ]
